# Generated by Django 3.0.5 on 2020-04-30 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 13, 35, 20, 590256, tzinfo=utc)),
        ),
    ]
