# Generated by Django 3.0.5 on 2020-04-30 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200430_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
