# Generated by Django 3.0.5 on 2020-05-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200501_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='end_time',
            new_name='end_utc_time',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='start_time',
            new_name='start_utc_time',
        ),
    ]
